---
- name: Verify Nginx servers on environment
  hosts: "tag_Environment_{{env}}"
  gather_facts: false
  pre_tasks:
   - include_vars: env_vars/{{env}}.yml
  tasks: 
    - include: 'roles/verify_nginx/tasks/main.yml'
